In [ ]:
!apt-get update -qq
!apt-get install -y -qq tesseract-ocr
!apt-get install -y -qq tesseract-ocr-hin
!apt-get install -y -qq tesseract-ocr-asm

!pip install -q opencv-python-headless pytesseract pandas openpyxl pillow matplotlib

W: Skipping acquire of configured file 'main/source/Sources' as repository 'https://r2u.stat.illinois.edu/ubuntu noble InRelease' does not seem to provide it (sources.list entry misspelt?)
Selecting previously unselected package tesseract-ocr-hin.
(Reading database ... 122815 files and directories currently installed.)
Preparing to unpack .../tesseract-ocr-hin_1%3a4.1.0-2_all.deb ...
Unpacking tesseract-ocr-hin (1:4.1.0-2) ...
Setting up tesseract-ocr-hin (1:4.1.0-2) ...
Selecting previously unselected package tesseract-ocr-asm.
(Reading database ... 122819 files and directories currently installed.)
Preparing to unpack .../tesseract-ocr-asm_1%3a4.1.0-2_all.deb ...
Unpacking tesseract-ocr-asm (1:4.1.0-2) ...
Setting up tesseract-ocr-asm (1:4.1.0-2) ...

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import os

DATASET_DIR = "/content/drive/MyDrive/FloodSense_OCR_NLP_Dataset"

if not os.path.exists(DATASET_DIR):
    raise FileNotFoundError(f"Dataset folder not found: {DATASET_DIR}")

print("Dataset folder found!")
print("Files:", len(os.listdir(DATASET_DIR)))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Dataset folder found!
Files: 35

In [ ]:
import os
import cv2
import pandas as pd
import pytesseract

from difflib import SequenceMatcher

GROUND_TRUTH_PATH = os.path.join(
    DATASET_DIR,
    "FloodSense_Dataset_Ground_Truth.csv"
)

if not os.path.exists(GROUND_TRUTH_PATH):
    raise FileNotFoundError(GROUND_TRUTH_PATH)

ground_truth = pd.read_csv(GROUND_TRUTH_PATH)

required_columns = ["Image_Name", "Original_Text"]

for column in required_columns:
    if column not in ground_truth.columns:
        raise ValueError(f"Missing required column: {column}")

print("Ground-truth records:", len(ground_truth))
print("Installed Tesseract languages:", pytesseract.get_languages(config=""))
print("Image files:", sum(
    f.lower().endswith((".png", ".jpg", ".jpeg"))
    for f in os.listdir(DATASET_DIR)
))

display(ground_truth.head())

Ground-truth records: 30
Installed Tesseract languages: ['asm', 'eng', 'hin', 'osd']
Image files: 30

,Image_Name,Language,Original_Text,Expected_Needs,Expected_Keywords,Expected_Location,Expected_People_Count,Expected_Time,Expected_Urgency_Level,Image_Type
0,FS_EN_001.png,English,HELP! Eight people are trapped on the first fl...,rescue,trapped; rescue boat; Water is still rising; c...,Riverbank Village,8.0,NaN,high,Direct emergency request
1,FS_EN_002.png,English,We are stuck at home because the road is flood...,water; food,drinking water; food packets; road is flooded;...,NaN,NaN,by tomorrow morning,medium,Direct emergency request
2,FS_EN_003.png,English,AMBULANCE REQUIRED URGENTLY\nA pregnant woman ...,medical,ambulance; pregnant woman; in labour; boat amb...,North Colony,NaN,before 9:00 PM tonight,high,Direct emergency request
3,FS_EN_004.png,English,Road to Green Valley Cut Off as River Floods F...,water; food; evacuation,under waist-deep water; drinking water; water ...,Green Valley,400.0,since Tuesday; until Friday,medium,Newspaper-style report
4,FS_EN_005.png,English,Blankets and Warm Clothes Needed at Sunrise Na...,clothing,blankets; warm clothes; baby clothing; wet clo...,Sunrise Nagar,120.0,by Sunday,low,Newspaper-style report

In [ ]:
import re

def normalize_text(text):
    text = str(text).lower()
    text = re.sub(r"\s+", " ", text)
    return text.strip()


def similarity_score(expected, extracted):
    expected = normalize_text(expected)
    extracted = normalize_text(extracted)

    if not expected:
        return 100.0 if not extracted else 0.0

    return round(
        SequenceMatcher(
            None,
            expected,
            extracted
        ).ratio() * 100,
        2
    )

In [ ]:
LANGUAGE_MAP = {
    "EN": ["eng"],
    "HI": ["hin"],
    "AS": ["asm"],
    "CM": ["eng+hin", "hin+eng"],
    "AS_EN": ["eng+asm", "asm+eng"]
}


def get_image_language(image_name):
    name = image_name.upper()

    if "_AS_EN_" in name:
        return LANGUAGE_MAP["AS_EN"]
    elif "_CM_" in name:
        return LANGUAGE_MAP["CM"]
    elif "_EN_" in name:
        return LANGUAGE_MAP["EN"]
    elif "_HI_" in name:
        return LANGUAGE_MAP["HI"]
    elif "_AS_" in name:
        return LANGUAGE_MAP["AS"]

    return ["eng", "hin", "asm"]


def preprocess_image(gray, method):
    if method == "original":
        return gray

    if method == "otsu":
        _, result = cv2.threshold(
            gray,
            0,
            255,
            cv2.THRESH_BINARY + cv2.THRESH_OTSU
        )
        return result

    if method == "adaptive":
        block_size = 31

        if min(gray.shape) < block_size:
            block_size = max(
                3,
                min(gray.shape) // 2 * 2 - 1
            )

        return cv2.adaptiveThreshold(
            gray,
            255,
            cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
            cv2.THRESH_BINARY,
            block_size,
            11
        )

    raise ValueError(f"Unknown preprocessing method: {method}")


def run_tesseract(image, language, psm):
    config = f"--oem 3 --psm {psm}"

    return pytesseract.image_to_string(
        image,
        lang=language,
        config=config
    ).strip()

In [ ]:
def adaptive_ocr(image_path, language_options):
    image = cv2.imread(image_path)

    if image is None:
        raise ValueError(f"Could not read image: {image_path}")

    image = cv2.resize(
        image,
        None,
        fx=2,
        fy=2,
        interpolation=cv2.INTER_CUBIC
    )

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    candidates = []

    # Full-image OCR
    for method in ["original", "otsu", "adaptive"]:
        processed = preprocess_image(gray, method)

        for language in language_options:
            for psm in [3, 6, 11]:
                try:
                    text = run_tesseract(
                        processed,
                        language,
                        psm
                    )

                    candidates.append({
                        "Layout": "full_image",
                        "Preprocessing": method,
                        "Language": language,
                        "PSM": psm,
                        "Extracted_Text": text
                    })

                except pytesseract.TesseractError as error:
                    print(
                        f"Skipped {method}/{language}/PSM{psm}: {error}"
                    )

    # Two-column OCR
    height, width = gray.shape
    midpoint = width // 2
    gap = max(1, int(width * 0.015))

    left = gray[:, :max(1, midpoint - gap)]
    right = gray[:, min(width, midpoint + gap):]

    if right.size > 0:
        for method in ["original", "otsu"]:
            left_processed = preprocess_image(left, method)
            right_processed = preprocess_image(right, method)

            for language in language_options:
                try:
                    left_text = run_tesseract(
                        left_processed,
                        language,
                        6
                    )

                    right_text = run_tesseract(
                        right_processed,
                        language,
                        6
                    )

                    candidates.append({
                        "Layout": "two_columns",
                        "Preprocessing": method,
                        "Language": language,
                        "PSM": 6,
                        "Extracted_Text": (
                            left_text + "\n" + right_text
                        ).strip()
                    })

                except pytesseract.TesseractError as error:
                    print(
                        f"Skipped column OCR {method}/{language}: {error}"
                    )

    return candidates


results = []

for _, row in ground_truth.iterrows():
    image_name = str(row["Image_Name"])
    expected_text = str(row["Original_Text"])

    image_path = os.path.join(DATASET_DIR, image_name)

    if not os.path.exists(image_path):
        print("Missing image:", image_name)
        continue

    try:
        candidates = adaptive_ocr(
            image_path,
            get_image_language(image_name)
        )

        if not candidates:
            print("No OCR candidates generated:", image_name)
            continue

        for candidate in candidates:
            candidate["Image_Name"] = image_name

            candidate["Similarity_Percent"] = similarity_score(
                expected_text,
                candidate["Extracted_Text"]
            )

        best = max(
            candidates,
            key=lambda item: item["Similarity_Percent"]
        )

        results.append(best)

        print(
            f"{image_name}: "
            f"{best['Similarity_Percent']:.2f}% | "
            f"{best['Layout']} | "
            f"{best['Preprocessing']} | "
            f"{best['Language']} | "
            f"PSM {best['PSM']}"
        )

    except Exception as error:
        print(f"Error processing {image_name}: {error}")


results_df = pd.DataFrame(results)

print("\nImages evaluated:", len(results_df))

print(
    "Baseline mean text similarity:",
    round(results_df["Similarity_Percent"].mean(), 2),
    "%"
)

display(
    results_df[
        [
            "Image_Name",
            "Similarity_Percent",
            "Layout",
            "Preprocessing",
            "Language",
            "PSM"
        ]
    ].sort_values("Image_Name")
)

FS_EN_001.png: 100.00% | full_image | original | eng | PSM 3
FS_EN_002.png: 100.00% | full_image | original | eng | PSM 3
FS_EN_003.png: 100.00% | full_image | original | eng | PSM 3
FS_EN_004.png: 95.24% | two_columns | original | eng | PSM 6
FS_EN_005.png: 100.00% | full_image | original | eng | PSM 3
FS_EN_006.png: 100.00% | full_image | original | eng | PSM 3
FS_EN_007.png: 100.00% | full_image | original | eng | PSM 3
FS_EN_008.png: 100.00% | full_image | adaptive | eng | PSM 6
FS_HI_001.png: 97.35% | full_image | original | hin | PSM 11
FS_HI_002.png: 98.82% | full_image | original | hin | PSM 3
FS_HI_003.png: 99.41% | full_image | adaptive | hin | PSM 11
FS_HI_004.png: 99.13% | full_image | original | hin | PSM 3
FS_HI_005.png: 98.93% | full_image | adaptive | hin | PSM 6
FS_HI_006.png: 98.93% | full_image | original | hin | PSM 3
FS_HI_007.png: 99.26% | full_image | original | hin | PSM 11
FS_HI_008.png: 98.34% | full_image | original | hin | PSM 3
FS_AS_001.png: 99.69% | full_image | otsu | asm | PSM 11
FS_AS_002.png: 99.65% | full_image | adaptive | asm | PSM 3
FS_AS_003.png: 99.64% | full_image | original | asm | PSM 3
FS_AS_004.png: 98.05% | full_image | original | asm | PSM 6
FS_AS_005.png: 100.00% | full_image | original | asm | PSM 6
FS_AS_006.png: 100.00% | full_image | otsu | asm | PSM 3
FS_AS_007.png: 99.58% | full_image | original | asm | PSM 3
FS_CM_001.png: 95.01% | full_image | adaptive | eng+hin | PSM 11
FS_CM_002.png: 100.00% | full_image | original | hin+eng | PSM 3
FS_CM_003.png: 42.86% | full_image | original | eng+hin | PSM 11
FS_CM_004.png: 79.87% | two_columns | otsu | hin+eng | PSM 6
FS_CM_005.png: 29.07% | full_image | adaptive | eng+hin | PSM 3
FS_CM_006.png: 100.00% | full_image | original | eng+hin | PSM 3
FS_CM_007.png: 96.31% | full_image | original | eng+hin | PSM 3

Images evaluated: 30
Baseline mean text similarity: 94.17 %

       Image_Name  Similarity_Percent       Layout Preprocessing Language  PSM
16  FS_AS_001.png               99.69   full_image          otsu      asm   11
17  FS_AS_002.png               99.65   full_image      adaptive      asm    3
18  FS_AS_003.png               99.64   full_image      original      asm    3
19  FS_AS_004.png               98.05   full_image      original      asm    6
20  FS_AS_005.png              100.00   full_image      original      asm    6
21  FS_AS_006.png              100.00   full_image          otsu      asm    3
22  FS_AS_007.png               99.58   full_image      original      asm    3
23  FS_CM_001.png               95.01   full_image      adaptive  eng+hin   11
24  FS_CM_002.png              100.00   full_image      original  hin+eng    3
25  FS_CM_003.png               42.86   full_image      original  eng+hin   11
26  FS_CM_004.png               79.87  two_columns          otsu  hin+eng    6
27  FS_CM_005.png               29.07   full_image      adaptive  eng+hin    3
28  FS_CM_006.png              100.00   full_image      original  eng+hin    3
29  FS_CM_007.png               96.31   full_image      original  eng+hin    3
0   FS_EN_001.png              100.00   full_image      original      eng    3
1   FS_EN_002.png              100.00   full_image      original      eng    3
2   FS_EN_003.png              100.00   full_image      original      eng    3
3   FS_EN_004.png               95.24  two_columns      original      eng    6
4   FS_EN_005.png              100.00   full_image      original      eng    3
5   FS_EN_006.png              100.00   full_image      original      eng    3
6   FS_EN_007.png              100.00   full_image      original      eng    3
7   FS_EN_008.png              100.00   full_image      adaptive      eng    6
8   FS_HI_001.png               97.35   full_image      original      hin   11
9   FS_HI_002.png               98.82   full_image      original      hin    3
10  FS_HI_003.png               99.41   full_image      adaptive      hin   11
11  FS_HI_004.png               99.13   full_image      original      hin    3
12  FS_HI_005.png               98.93   full_image      adaptive      hin    6
13  FS_HI_006.png               98.93   full_image      original      hin    3
14  FS_HI_007.png               99.26   full_image      original      hin   11
15  FS_HI_008.png               98.34   full_image      original      hin    3

In [ ]:
targeted_configs = {
    "FS_CM_005.png": {
        "preprocessing": "otsu",
        "language": "eng+asm",
        "psm": 6
    },
    "FS_CM_003.png": {
        "preprocessing": "grayscale",
        "language": "asm+eng",
        "psm": 3
    }
}

targeted_results = []

for image_name, settings in targeted_configs.items():
    image_path = os.path.join(DATASET_DIR, image_name)

    image = cv2.imread(image_path)

    if image is None:
        raise FileNotFoundError(image_path)

    image = cv2.resize(
        image,
        None,
        fx=2,
        fy=2,
        interpolation=cv2.INTER_CUBIC
    )

    gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

    if settings["preprocessing"] == "otsu":
        _, processed = cv2.threshold(
            gray,
            0,
            255,
            cv2.THRESH_BINARY + cv2.THRESH_OTSU
        )
    else:
        processed = gray

    extracted_text = pytesseract.image_to_string(
        processed,
        lang=settings["language"],
        config=f"--oem 3 --psm {settings['psm']}"
    ).strip()

    reference = ground_truth[
        ground_truth["Image_Name"] == image_name
    ]

    if reference.empty:
        raise ValueError(f"Ground truth not found: {image_name}")

    expected_text = str(reference.iloc[0]["Original_Text"])

    score = similarity_score(
        expected_text,
        extracted_text
    )

    targeted_results.append({
        "Image_Name": image_name,
        "Similarity_Percent": score,
        "Preprocessing": settings["preprocessing"],
        "Language": settings["language"],
        "PSM": settings["psm"],
        "Extracted_Text": extracted_text
    })

targeted_results_df = pd.DataFrame(targeted_results)

display(
    targeted_results_df[
        [
            "Image_Name",
            "Similarity_Percent",
            "Preprocessing",
            "Language",
            "PSM"
        ]
    ]
)

      Image_Name  Similarity_Percent Preprocessing Language  PSM
0  FS_CM_005.png               98.69          otsu  eng+asm    6
1  FS_CM_003.png               96.95     grayscale  asm+eng    3

In [ ]:
image_name = "FS_CM_004.png"
image_path = os.path.join(DATASET_DIR, image_name)

image = cv2.imread(image_path)

if image is None:
    raise FileNotFoundError(image_path)

image = cv2.resize(
    image,
    None,
    fx=2,
    fy=2,
    interpolation=cv2.INTER_CUBIC
)

gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

_, otsu = cv2.threshold(
    gray,
    0,
    255,
    cv2.THRESH_BINARY + cv2.THRESH_OTSU
)

height, width = otsu.shape

# OCR the headline separately
headline = otsu[:int(height * 0.35), :]

headline_text = pytesseract.image_to_string(
    headline,
    lang="eng+hin",
    config="--oem 3 --psm 11"
).strip()

reference = ground_truth[
    ground_truth["Image_Name"] == image_name
]

if reference.empty:
    raise ValueError("Ground truth not found for FS_CM_004.png")

expected_text = str(reference.iloc[0]["Original_Text"])

# Test body starting positions
crop_positions = [30, 33, 35, 37]
crop_results = []

for start_percent in crop_positions:
    body = otsu[int(height * start_percent / 100):, :]

    body_width = body.shape[1]
    midpoint = body_width // 2

    left_column = body[:, :midpoint]
    right_column = body[:, midpoint:]

    left_text = pytesseract.image_to_string(
        left_column,
        lang="hin+eng",
        config="--oem 3 --psm 6"
    ).strip()

    right_text = pytesseract.image_to_string(
        right_column,
        lang="hin+eng",
        config="--oem 3 --psm 6"
    ).strip()

    combined_text = (
        headline_text.strip()
        + "\n"
        + left_text.strip()
        + "\n"
        + right_text.strip()
    )

    score = similarity_score(
        expected_text,
        combined_text
    )

    crop_results.append({
        "Body_Crop_Start_Percent": start_percent,
        "Similarity_Percent": round(score, 2),
        "Extracted_Text": combined_text
    })

crop_results_df = pd.DataFrame(crop_results)

display(
    crop_results_df[
        ["Body_Crop_Start_Percent", "Similarity_Percent"]
    ].sort_values("Similarity_Percent", ascending=False)
)

   Body_Crop_Start_Percent  Similarity_Percent
3                       37               95.48
2                       35               93.81
0                       30               88.32
1                       33               82.16

In [ ]:
# Preserve the baseline results
final_results_df = results_df.copy()

# Replace results for FS_CM_003 and FS_CM_005
for image_name in ["FS_CM_003.png", "FS_CM_005.png"]:
    new_result = targeted_results_df[
        targeted_results_df["Image_Name"] == image_name
    ]

    if new_result.empty:
        raise ValueError(f"Missing targeted OCR result: {image_name}")

    new_result = new_result.iloc[0]
    mask = final_results_df["Image_Name"] == image_name

    for column in [
        "Similarity_Percent",
        "Preprocessing",
        "Language",
        "PSM",
        "Extracted_Text"
    ]:
        if column in final_results_df.columns:
            final_results_df.loc[mask, column] = new_result[column]

# Replace the result for FS_CM_004
best_crop_row = crop_results_df.loc[
    crop_results_df["Similarity_Percent"].idxmax()
]

mask = final_results_df["Image_Name"] == "FS_CM_004.png"

final_results_df.loc[mask, "Similarity_Percent"] = (
    best_crop_row["Similarity_Percent"]
)

final_results_df.loc[mask, "Layout"] = "headline_body_columns"
final_results_df.loc[mask, "Preprocessing"] = "otsu"
final_results_df.loc[mask, "Language"] = "hin+eng"
final_results_df.loc[mask, "PSM"] = 6
final_results_df.loc[mask, "Extracted_Text"] = (
    best_crop_row["Extracted_Text"]
)

# Validate the final results
final_results_df["Similarity_Percent"] = pd.to_numeric(
    final_results_df["Similarity_Percent"],
    errors="coerce"
)

print("Total rows:", len(final_results_df))
print("Unique images:", final_results_df["Image_Name"].nunique())
print("Missing scores:", final_results_df["Similarity_Percent"].isna().sum())

print(
    "\nFinal mean text similarity:",
    round(final_results_df["Similarity_Percent"].mean(), 2),
    "%"
)

display(
    final_results_df[
        [
            "Image_Name",
            "Similarity_Percent",
            "Layout",
            "Preprocessing",
            "Language",
            "PSM"
        ]
    ].sort_values("Image_Name")
)

Total rows: 30
Unique images: 30
Missing scores: 0

Final mean text similarity: 98.82 %

,Image_Name,Similarity_Percent,Layout,Preprocessing,Language,PSM
16,FS_AS_001.png,99.69,full_image,otsu,asm,11
17,FS_AS_002.png,99.65,full_image,adaptive,asm,3
18,FS_AS_003.png,99.64,full_image,original,asm,3
19,FS_AS_004.png,98.05,full_image,original,asm,6
20,FS_AS_005.png,100.00,full_image,original,asm,6
21,FS_AS_006.png,100.00,full_image,otsu,asm,3
22,FS_AS_007.png,99.58,full_image,original,asm,3
23,FS_CM_001.png,95.01,full_image,adaptive,eng+hin,11
24,FS_CM_002.png,100.00,full_image,original,hin+eng,3
25,FS_CM_003.png,96.95,full_image,grayscale,asm+eng,3
26,FS_CM_004.png,95.48,headline_body_columns,otsu,hin+eng,6
27,FS_CM_005.png,98.69,full_image,otsu,eng+asm,6
28,FS_CM_006.png,100.00,full_image,original,eng+hin,3
29,FS_CM_007.png,96.31,full_image,original,eng+hin,3
0,FS_EN_001.png,100.00,full_image,original,eng,3
1,FS_EN_002.png,100.00,full_image,original,eng,3
2,FS_EN_003.png,100.00,full_image,original,eng,3
3,FS_EN_004.png,95.24,two_columns,original,eng,6
4,FS_EN_005.png,100.00,full_image,original,eng,3
5,FS_EN_006.png,100.00,full_image,original,eng,3
6,FS_EN_007.png,100.00,full_image,original,eng,3
7,FS_EN_008.png,100.00,full_image,adaptive,eng,6
8,FS_HI_001.png,97.35,full_image,original,hin,11
9,FS_HI_002.png,98.82,full_image,original,hin,3
10,FS_HI_003.png,99.41,full_image,adaptive,hin,11
11,FS_HI_004.png,99.13,full_image,original,hin,3
12,FS_HI_005.png,98.93,full_image,adaptive,hin,6
13,FS_HI_006.png,98.93,full_image,original,hin,3
14,FS_HI_007.png,99.26,full_image,original,hin,11
15,FS_HI_008.png,98.34,full_image,original,hin,3

In [ ]:
output_path = os.path.join(
    DATASET_DIR,
    "FloodSense_OCR_Final_Results.csv"
)

final_results_df.to_csv(
    output_path,
    index=False,
    encoding="utf-8-sig"
)

print("Final results saved to:", output_path)

Final results saved to: /content/drive/MyDrive/FloodSense_OCR_NLP_Dataset/FloodSense_OCR_Final_Results.csv

In [ ]:
from google.colab import files

# Save final results to CSV
final_results_df.to_csv("final_ocr_results.csv", index=False, encoding="utf-8-sig")

# Download the file
files.download("final_ocr_results.csv")